greeting: Welcome,
name: anonymous
server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

database:
    # the name of the JDBC driver, mysql
    driverClass: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
    # the username
    user: root
    # the password
    password:
    # the JDBC URL; the database
    url: jdbc:mysql://localhost:3306/trial

    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect